### ISSUE TITLE
ChannelBot just flatout ignored my commands.

### ISSUE THREAD

**Issue by FMFields** [PintTheDragon/ChannelMessage#3] opened 2020-09-25 11:49 UTC

**Comment by PintTheDragon** [comment] 2020-09-26 04:52
Everything is working fine on my end. Make sure that it has permissions to speak in and read the current channel you're in, and try mentioning it instead of using a prefix (``@ChannelMessage help`` instead of ``.help``). Let me know how that goes!

**Comment by PintTheDragon** [comment] 2020-09-28 19:19
I haven't gotten any response and I can't reproduce this issue so I'm closing this now.

**Closed as completed by PintTheDragon** 2020-09-28 19:19 UTC
